package com.papaya.design.platform.bot.image.bot.domain

enum class UserState {
    READY_FOR_CMD,
    WAITING_FOR_END_OF_PHOTO_GENERATION,

    REALISTIC_INTERIOR_WAITING_FOR_PHOTO,

    EXTENDED_REALISTIC_INTERIOR_WAITING_FOR_PHOTO,
    EXTENDED_REALISTIC_INTERIOR_WAITING_FOR_USER_PROMPT,
    EXTENDED_REALISTIC_INTERIOR_WAITING_ADDITIONAL_PHOTO,

    ROOM_UPGRADE_WAITING_FOR_PHOTO,
    ROOM_UPGRADE_WAITING_FOR_USER_OPTION,

    PLANNED_REALISTIC_INTERIOR_WAITING_FOR_PHOTO,
    PLANNED_REALISTIC_INTERIOR_WAITING_FOR_USER_OPTION,
}
